server:
  port: 8089

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.106.95.33:3306/dahai
    username: root
    password: DqbSN)*05g50
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    port: 25
    protocol: smtp
    username: 17620037710@163.com
    password: abc123456

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  type-aliases-package: com.dahai.dao  # 注意：对应实体类的路径
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
